// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";

import Notification from "@stimulus-components/notification";
application.register("notification", Notification);

import AutoSubmit from "@stimulus-components/auto-submit";
application.register("auto-submit", AutoSubmit);

import AutocompleteController from "./autocomplete_controller";
application.register("autocomplete", AutocompleteController);

import CategoriesDialogController from "./categories_dialog_controller";
application.register("categories-dialog", CategoriesDialogController);

import CategoryIconController from "./category_icon_controller";
application.register("category-icon", CategoryIconController);

import ComboboxController from "./combobox_controller";
application.register("combobox", ComboboxController);

import DividerController from "./divider_controller";
application.register("divider", DividerController);

import MoneyInputController from "./money_input_controller";
application.register("money-input", MoneyInputController);

import RelativeDateController from "./relative_date_controller";
application.register("relative-date", RelativeDateController);

import SortedController from "./sorted_controller";
application.register("sorted", SortedController);

import Transactions__DialogController from "./transactions/dialog_controller";
application.register("transactions--dialog", Transactions__DialogController);
