// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";

import CategoriesDialogController from "./categories_dialog_controller";
application.register("categories-dialog", CategoriesDialogController);

import TransactionsDialogController from "./transactions_dialog_controller";
application.register("transactions-dialog", TransactionsDialogController);

import CategoryIconController from "./category_icon_controller";
application.register("category-icon", CategoryIconController);

import SortedController from "./sorted_controller";
application.register("sorted", SortedController);

import DividerController from "./divider_controller";
application.register("divider", DividerController);

import MoneyInputController from "./money_input_controller";
application.register("money-input", MoneyInputController);
