default: &default
  adapter: solid_cable
  connects_to:
    database:
      writing: ops
      reading: ops

development:
  <<: *default
  silence_polling: true

test:
  adapter: test

production:
  <<: *default
